import type { BoardData } from '@/lib/board/types'

export const mockBoardData: BoardData = {
  people: [{ id: 'p1', name: 'Hafsham', email: '', profileId: null, isActive: true }],
  profiles: [{ id: 'u1', email: 'admin@caspiands.com', fullName: 'Bharg', role: 'admin', isActive: true }],
  settings: { year: 2026, target: 7000000, financeRevenue: 4500000, financeAsOf: '2026-10-01' },
  commitments: [],
  opps: [
    {
      id: 'o1',
      account: 'BBSG',
      item: 'Q4 quotations',
      segment: 'Mixed',
      ownerId: 'p1',
      ownerIds: ['p1'],
      stage: 'Quote sent',
      value: 262000,
      revenueYear: 2026,
      quoteNo: '',
      quoteDate: null,
      loaDate: null,
      invoiceMonth: null,
      startDate: null,
      probability: null,
      nextStep: 'Follow up',
      nextOwnerId: 'p1',
      nextDate: '2026-10-07',
      link: '',
      notes: '',
      stageSince: '2026-10-01T10:00:00Z',
      createdAt: '2026-10-01T10:00:00Z',
      createdBy: 'u1',
      updatedAt: '2026-10-01T10:00:00Z',
      updatedBy: 'u1',
    },
  ],
  prospects: [],
  reviews: [],
  history: [],
}
